# Generated by Django 4.0.3 on 2022-03-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phone_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
