# Generated by Django 4.0.3 on 2022-03-01 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 0, 0)),
        ),
    ]
