# Generated by Django 4.0.3 on 2022-03-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phone_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
