# Generated by Django 4.0.3 on 2022-03-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_phone_has_whatsapp_phone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
