version: "3.9"

services:
  web:
    build: .
    command: gunicorn --certfile=/code/fullchain.pem --keyfile=/code/privkey.pem --bind 0.0.0.0:443 project.wsgi:application
    volumes:
      - .:/code
    ports:
      - "443:443"
    env_file:
      - .env

